### ISSUE TITLE
Incomplete rendering during drag operations in QwtPlot

### ISSUE THREAD

**Issue by LiZhaoyue888** [opencor/qwt#10]
#### Environment
- **Qwt version**: 1.0
- **Qt version**: 5.9.9
- **Operating System**: Windows 11

#### Steps to Reproduce
1. Open the application with a QwtPlot widget.
2. Begin a drag operation to resize or move the plot.
3. Observe the rendering of the plot area.

#### Expected Behavior
The plot should render smoothly and completely during and after the drag operation.

#### Actual Behavior
During dragging, parts of the plot are not rendered, leaving blank areas that only fill in once the drag operation is completed.

#### Screenshots
![屏幕截图 2024-08-22 170518](https://github.com/user-attachments/assets/7e899c89-e911-473f-b211-ed19417ee51c)
![屏幕截图 2024-08-22 170518](https://github.com/user-attachments/assets/3ad3d526-8b0c-4f5d-a083-9ee0f04643fe)

#### Additional Information
No similar issues found. Temporary workaround has been to force a replot after the drag operation, but this results in flickering.

**Comment by agarny** [comment]
Sorry but this repo is only a fork of the original Qwt repo. For support, please have a look [here](https://qwt.sourceforge.io/#support).
