### ISSUE TITLE
Crash in qwt_date_scale_engine.cpp

### ISSUE THREAD

**Issue by oss81** [opencor/qwt#3]
Hi,

the function 

`static QList< double > qwtDstTicks( const QDateTime& dateTime,
    int secondsMajor, int secondsMinor )`

crashes when `secondsMajor` is 0

I guess the code at the start
`
if ( secondsMinor <= 0 )
        QList< double >();
`

should be 
`
if ( secondsMinor <= 0 )
        return QList< double >();
`

**Comment by agarny** [comment]
Sorry for not noticing your issue before, but you may have since noticed that this repo is only a fork of the original Qwt repo. For support, please have a look [here](https://qwt.sourceforge.io/#support).
