### ISSUE TITLE
Is it possible to draw a closed grid without any spur?

### ISSUE THREAD

**Issue by AlexLuya** [opencor/qwt#7]
As you can see,the grid of QWT has many spurs by default,and below grid is closed by a frame which is added manually by myself in ppt. Question is:

Is it possible to draw a closed grid in QWT?

[![demo image][1]][1]

  [1]: https://i.stack.imgur.com/2qJ0u.png

**Comment by agarny** [comment]
Sorry, but this is not the official repository for Qwt. This is "only" a fork that is used in another project. Please have a look at https://qwt.sourceforge.io/.
